services:
  homarr:
    container_name: Homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr/appdata:/home/homepage/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7575:7575"
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}

  dashdot:
    container_name: Dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    volumes:
      - /:/mnt/host:ro

  opencloud:
    container_name: OpenCloud
    image: opencloudeu/opencloud-rolling:latest
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - $HOME/opencloud/opencloud-config:/etc/opencloud
      - $HOME/opencloud/opencloud-data:/var/lib/opencloud
    environment:
      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=http://homelab:9200
      - IDM_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OC_JWT_SECRET=${OPENCLOUD_SECRET_KEY}

  n8n:
    container_name: N8N
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data: {}
