services:
  homarr:
    container_name: Homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr/appdata:/home/homepage/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7575:7575"
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}

  dashdot:
    container_name: Dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    volumes:
      - /:/mnt/host:ro

  filebrowser:
    container_name: Filebrowser
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - filebrowser_data:/data/cloud
      - /:/data/mount
      - ${HOME}:/data/home
      - filebrowser_config:/config
    restart: always

  code-server:
    container_name: Code-server
    user: "1000:1000"
    volumes:
      - $HOME/.local:/home/coder/.local
      - $HOME/.config:/home/coder/.config
      - ./:/home/coder/project
    environment:
      - DOCKER_USER=$USER

  n8n:
    container_name: N8N
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data: {}
  filebrowser_data: {}
  filebrowser_config: {}
